fix: accessibility
lenyeg/mkt-osmarjr.adv.br pull request #4
Opened 2022-10-31 17:44 UTC by lukinhas711

2022-10-31 19:38 UTC, andrevandal requested changes

2022-10-31 19:38 UTC, andrevandal commented on src/components/vue/TabNavegation.vue
> +                    <img src="/images/check-shild.svg" alt="check shild icon" class="w-[18px] h-[18px]" />
no caso de ícones colocado como imagem, você pode colocar o alt vazio (`alt=""`), o mais importante nesse caso seria colocar o `width` e o `height` via atributo.

2022-10-31 19:38 UTC, andrevandal commented on src/components/TheFooter.astro
> +            <span class="sr-only">facebook</span>
mandou bem!

2022-10-31 19:38 UTC, andrevandal commented on src/components/TheFooter.astro
> +        <span class="sr-only">lenyeg</span><Icon
aqui no rodapé, a logo da lenyeg pode ser uma imagem em svg com width e height definidos e com o alt `Lenyeg`

2022-10-31 19:38 UTC, andrevandal commented on src/components/TheHeader.astro
> +        <img
esse é o modelo que você usará no footer, mas com a imagem em svg

2022-10-31 19:38 UTC, andrevandal commented on src/components/vue/TabNavegation.vue
> +                      <svg class="-rotate-90 group-open:rotate-0 duration-150 h-6 w-6 transform"
poderia moder para astro-icons?

2022-10-31 19:38 UTC, andrevandal commented on src/components/vue/TabNavegation.vue
> +                    <svg class="-rotate-90 group-open:rotate-0 duration-150 h-6 w-6 transform"
pode mover para o astro-icons também?

2022-10-31 19:38 UTC, andrevandal commented on src/components/vue/TabNavegation.vue
>    </div>
nesse arquivo, todos os `check-shild.svg` devem ser colocados via astro-icons. :D

2022-10-31 19:38 UTC, andrevandal commented on src/components/vue/ToggleMenu.vue
>              <span class="sr-only">Osmar Júnior - Advogado</span>
como colocou o alt na imagem a baixo, pode remover esse span

2022-11-01 17:00 UTC, lukinhas711 commented on src/components/vue/TabNavegation.vue
> +                    <img src="/images/check-shild.svg" alt="check shild icon" class="w-[18px] h-[18px]" />
é que la no relatorio esta pedindo o alt tbm, mas então romove os alt ?

2022-11-01 17:04 UTC, lukinhas711 commented on src/components/vue/TabNavegation.vue
> +                      <svg class="-rotate-90 group-open:rotate-0 duration-150 h-6 w-6 transform"
Acho que não funcionou quando tentei, o componente é feito em vue, mas posso implementar o BaseIcon aqui.

2022-11-07 13:14 UTC, andrevandal approved these changes

2022-11-07 13:14 UTC, merged